### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by jake-walker** [malvern-cads/hacman#1]
Create a new Python file and/or class for managing scoreboard stuff.

## Basic Stuff

- [x] Save and load the scoreboard from a JSON file
- [x] Function for adding an entry to the scoreboard including name, (school?) and score
- [x] Function for getting scoreboard entries which are sorted by highest score

## Extra

- [x] Create a web page with the scoreboard that refreshes every couple of minutes.

**Comment by 13lanet** [comment]
Scoreboard format
`[name, score, time, school]`
```json
[
  ["Tom", 69, 5.2, "The Chad"],
  ["Jake", 420, 20, "The Chad"],
  ["Ben", 3, 500, "The Chad"],
]
```
